SELECT 
MONTH(ORDERDATE) AS MONTH, 
LEFT(DATENAME(MONTH, ORDERDATE), 3) AS Month_Name, 
YEAR(ORDERDATE) AS SALES_YEAR, 
SUM(TOTALDUE) AS TOTAL_SALES
FROM v_CustomerSales
GROUP BY YEAR(ORDERDATE), MONTH(ORDERDATE), DATENAME(MONTH, ORDERDATE)
ORDER BY SALES_YEAR, MONTH