SELECT BUSINESSENTITYID, TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, SUFFIX, JOBTITLE, EMAILADDRESS, ADDRESSLINE1, ADDRESSLINE2, CITY, STATEPROVINCENAME, COUNTRYREGIONNAME, POSTALCODE, DEPARTMENT, 
  STARTDATE, CURRENT_YEAR, ANNIVERSARY_YEAR
FROM     v_Employee_StartDates
WHERE  (MONTH(STARTDATE) = @MONTH)