/*
Author:			
	Lynnetta Curtis
Report:			
	Anniversary Letters.rdl
Created:			
	Jan 2021
Purpose:		
	To create a view of specific employee data. 
Design Tool:	
	SSRS/Visual Studio 2019 Community Edition
DBMS:			
	SQL SERVER 2017, Developer Edition
DB:				
	AdventureWorks 2017
Retention:		
	KP PERM
*/

USE ADVENTUREWORKS2017
GO
IF OBJECT_ID('v_EmployeeData') IS NOT NULL
	DROP VIEW v_EmployeeData
GO
CREATE VIEW v_EmployeeData
AS
(SELECT
EMPLOYEE.BUSINESSENTITYID,
EMPLOYEE.TITLE,
EMPLOYEE.FIRSTNAME,
EMPLOYEE.MIDDLENAME,
EMPLOYEE.LASTNAME,
EMPLOYEE.SUFFIX,
EMPLOYEE.JOBTITLE,
EMAILADDRESS,
ADDRESSLINE1,
ADDRESSLINE2,
CITY,
STATEPROVINCENAME,
POSTALCODE,
COUNTRYREGIONNAME,
DEPARTMENT,
STARTDATE,
MONTH(STARTDATE) AS MONTH_ID,
DATENAME(month, STARTDATE) AS MONTH_NAME,
YEAR(DATEADD(year,10,STARTDATE)) AS CURRENT_YEAR,
10 AS ANNIVERSARY_YEAR
FROM HUMANRESOURCES.VEMPLOYEE AS Employee
JOIN HUMANRESOURCES.VEMPLOYEEDEPARTMENT AS Department
ON EMPLOYEE.BUSINESSENTITYID=DEPARTMENT.BUSINESSENTITYID
ORDER BY MONTH_ID, LASTNAME, FIRSTNAME, MIDDLENAME
OFFSET 0 ROWS)
